#! /bin/sh 
set -eux

COSMO_LIBDIR=$(realpath "./libcosmo")
HEADER_PATHS=$(realpath "./header_stubs")
CC="${CC:-gcc}"

if [ ! -f $COSMO_LIBDIR/cosmopolitan.h ]; then
    echo "<<<SUPERCONFIGURE>>> cosmopolitan.h does not exist in $COSMO_LIBDIR!!!!"
    exit 1
fi

echo "<<<SUPERCONFIGURE>>> cosmopolitan.h exists in $COSMO_LIBDIR, assuming other files exist as well"

echo "<<<SUPERCONFIGURE>>> Running configure with $CC"
LD_LIBRARY_PATH="" ./configure \
    --without-libiconv-prefix \
    --without-libintl-prefix \
    --disable-posix-spawn \
    --without-guile \
    CFLAGS="-O0 -g3 -Wall -Wno-strict-prototypes -Wno-unused-value \
      -std=c99 -static \
      -fno-pie -fno-omit-frame-pointer \
      -mno-red-zone -pg \
      -nostdinc -nostdlib \
      -I$HEADER_PATHS \
      -include $COSMO_LIBDIR/cosmopolitan.h" \
    LDFLAGS="-static -nostdlib -nostdinc \
      -fno-pie -mno-red-zone \
      -include $COSMO_LIBDIR/cosmopolitan.h" \
    LIBS="-fuse-ld=bfd \
      -Wl,-T,$COSMO_LIBDIR/ape.lds \
      -include $COSMO_LIBDIR/cosmopolitan.h \
      $COSMO_LIBDIR/crt.o \
      $COSMO_LIBDIR/ape.o \
      $COSMO_LIBDIR/cosmopolitan.a"


echo "<<<SUPERCONFIGURE>>> Running make"
make -j4
